name: CI/CD

on: [push, workflow_dispatch]

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          docker build --pull -t kooldev/php:7.4-nginx-oci8 7.4-nginx-oci8
          docker build --pull -t kooldev/php:7.4-nginx-oci8-prod 7.4-nginx-oci8-prod

      - name: Tests
        run: |
          docker run kooldev/php:7.4-nginx-oci8 php -r "extension_loaded('oci8') or die(1);"
          docker run kooldev/php:7.4-nginx-oci8-prod php -r "extension_loaded('oci8') or die(1);"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: github.ref == 'refs/heads/main' && github.repository == 'kool-dev/docker-php-oci8'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to DockerHub
        if: github.ref == 'refs/heads/main' && github.repository == 'kool-dev/docker-php-oci8'
        run: |
          docker push kooldev/php:7.4-nginx-oci8
          docker push kooldev/php:7.4-nginx-oci8-prod
