name: CI/CD

on: [push, workflow_dispatch]

env:
  DOCKER_BUILDKIT: 1

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['8.0', '8.1', '8.2', '8.3']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0

      - name: Build
        run: |
          docker build --pull -t kooldev/php:${{ matrix.version }}-oci8-nginx ${{ matrix.version }}-oci8-nginx
          docker build --pull -t kooldev/php:${{ matrix.version }}-oci8-nginx-prod ${{ matrix.version }}-oci8-nginx-prod

          docker build --pull -t kooldev/php:${{ matrix.version }}-oci8-swoole-nginx ${{ matrix.version }}-oci8-swoole-nginx
          docker build --pull -t kooldev/php:${{ matrix.version }}-oci8-swoole-nginx-prod ${{ matrix.version }}-oci8-swoole-nginx-prod

      - name: Tests
        run: |
          docker run kooldev/php:${{ matrix.version }}-oci8-nginx php -r "extension_loaded('oci8') or die(1);"
          docker run kooldev/php:${{ matrix.version }}-oci8-nginx-prod php -r "extension_loaded('oci8') or die(1);"

          docker run kooldev/php:${{ matrix.version }}-oci8-nginx php -r "extension_loaded('oci8') or die(1);"
          docker run kooldev/php:${{ matrix.version }}-oci8-nginx-prod php -r "extension_loaded('oci8') or die(1);"

          docker run kooldev/php:${{ matrix.version }}-oci8-swoole-nginx php -r "extension_loaded('oci8') or die(1);"
          docker run kooldev/php:${{ matrix.version }}-oci8-swoole-nginx-prod php -r "extension_loaded('oci8') or die(1);"

      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        if: github.ref == 'refs/heads/main' && github.repository == 'kool-dev/docker-php-oci8'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to DockerHub
        if: github.ref == 'refs/heads/main' && github.repository == 'kool-dev/docker-php-oci8'
        run: |
          docker push kooldev/php:${{ matrix.version }}-oci8-nginx
          docker push kooldev/php:${{ matrix.version }}-oci8-nginx-prod

          docker push kooldev/php:${{ matrix.version }}-oci8-swoole-nginx
          docker push kooldev/php:${{ matrix.version }}-oci8-swoole-nginx-prod
